### ISSUE TITLE
Use an existing CSV schema format?

### ISSUE THREAD

**Issue by harrisj** [onyxfish/lookup#13]
This is pretty awesome, and what I'm suggesting is possibly overkill, but I was wondering if you had considered using one of the CSV schema formats for specifying the fields in the CSV. These seem to be the two biggest ones out there:
- [CSV Schema](http://digital-preservation.github.io/csv-schema/)
- [JSON Table Schema](http://dataprotocols.org/json-table-schema/)

I will admit this seems like a bit of overkill for a CSV of states, but it might be useful if you wanted to automatically validate future changes or additions with an automated test and then you get CI for your CSV. For instance, [Goodtables](http://goodtables.okfnlabs.org/) is a validator that uses the JSON schema format (although it needs some work). [CSVLint](http://csvlint.io/) is another new entrant I haven't evaluated it but it also uses the JSON schema format (which seems like the one to consider now).

**Comment by onyxfish** [comment]
I did briefly consider this. Too be perfectly honest, I mostly just did what was expedient. Some things, like the history of contributors, don't obviously fit cleanly into those other formats, but they could probably be made to work. In general, I don't see much advantage in standards for these kinds of one-off microformats, however, your example of automated validation is a compelling case. I'll def consider it for the first breaking release, whenever that ends up being.

**Comment by harrisj** [comment]
I don't have a strong opinion on it myself and I'd rather have something real rather than waiting on conformance so it's up to you. I guess I'd also want to check if the tools are all they claim too and can be run locally.

**Comment by jpmckinney** [comment]
Closing as no bandwidth.
