### ISSUE TITLE
Should `columns` allow for more columns, and/or more metadata?

### ISSUE THREAD

**Issue by dannguyen** [onyxfish/lookup#4]
The documentation makes it seem as if `columns` will only allow for a key and value pair. But what if there's a 3-way lookup, e.g. "New York", "NY", "N.Y.", etc...I'm guessing that's alluded to here:

https://github.com/wireservice/lookup/issues/3

but is `key/colname`: `datatype` enough? Or rather, is the succinctness worth the limitation in expanding the format? 

I'm thinking of Census decade-to-decade lookup tables, in which sometimes later tracts incorporate a combination of past tracts, and this complexity would seemingly be needed to state at the `columns` level of metadata.

Also, having a "human readable full name" attribute for each column would be nice.

Anyway, I know these aren't easy questions with non-tradeoffs...but thanks for taking charge on this!

**Comment by onyxfish** [comment]
So, I've given this a lot of thought and here's what conclusions I've reached so far:
- Multi-column lookups make the metadata and repository structure extremely complicated. Although having a separate table for each possible lookup is also onerous, it seems ultimately to be preferable to building out a huge architecture for looking up the join relationships.
- Crosswalks (or whatever you call non 1:1 mappings) are a separate problem. As much as I'd love to have those in here, they don't clearly follow the same procedure as a typical lookup. Some more of my thoughts on this are [here](https://github.com/wireservice/agate-lookup/issues/1#issuecomment-180822252).
- I'm definitely open to expanding the metadata format and would very much appreciate any thoughts on what fields are important to include. A full name for columns seems very reasonable to me.

**Comment by onyxfish** [comment]
Human readable column names are now on master, so closing this out. Please reopen if you have other suggestions.
