### ISSUE TITLE
Should FIPS code columns be a Number data type? 

### ISSUE THREAD

**Issue by palewire** [onyxfish/lookup#6]
I say this because I often seen FIPS codes provided with leading zeros. Forcing everything to integers might be a workaround on that problem.

**Comment by onyxfish** [comment]
I do want to add an override to agate-lookup so Text fields can optionally be treated as Number for join purposes, but in the case of FIPS codes that doesn't work, for the reason described here: https://github.com/Quartz/bad-data-guide#text-has-been-converted-to-numbers

**Comment by onyxfish** [comment]
Here is the relevant agate-lookup ticket: https://github.com/wireservice/agate-lookup/issues/15
